#!/usr/bin/env bash

# Start this from the directory holding the json files
# arg is name of apk to build without .json
KIWIX_DIR=/mnt/hgfs/cesar/src/kiwix-build

# cd $KIWIX_DIR
# ./gen-custom-android-build.py /curation/iiab-factory/kiwix-apks/$1.json --on=armeabi
# cd -

python $KIWIX_DIR/kiwix-build.py --verbose --target-platform android_arm --android-custom-app $1.json
